version: '3.8'

services:
  # 1. PostgreSQL Ma'lumotlar bazasi
  db:
    image: postgres:15-alpine
    container_name: anime_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=anime_db
      - POSTGRES_USER=anime_user
      - POSTGRES_PASSWORD=anime_password
    restart: always

  # 2. Django Web Sayti (Gunicorn orqali)
  web:
    build: .
    container_name: anime_django_web
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=anime_db
      - DB_USER=anime_user
      - DB_PASSWORD=anime_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    restart: always

  # 3. Aiogram Telegram Bot
  bot:
    build: .
    container_name: anime_telegram_bot
    command: python main.py
    volumes:
      - .:/app
    environment:
      - DB_NAME=anime_db
      - DB_USER=anime_user
      - DB_PASSWORD=anime_password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
      - web
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: