# Generated by Django 6.0.7 on 2026-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Anime nomi')),
                ('code', models.IntegerField(unique=True, verbose_name='Anime kodi')),
                ('file_id', models.CharField(max_length=550, verbose_name='Telegram Video File ID')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
            ],
            options={
                'verbose_name': 'Anime',
                'verbose_name_plural': 'Animelar',
            },
        ),
    ]
