# Generated by Django 6.0.7 on 2026-07-31 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='caption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='file_id',
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(default=1, verbose_name='Fasl (Sezon)')),
                ('episode_number', models.IntegerField(verbose_name='Qism raqami')),
                ('file_id', models.CharField(max_length=550, verbose_name='Telegram Video File ID')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='bot_app.anime', verbose_name='Anime')),
            ],
            options={
                'verbose_name': 'Qism',
                'verbose_name_plural': 'Qismlar',
                'unique_together': {('anime', 'season', 'episode_number')},
            },
        ),
    ]
