# Generated by Django 6.0.7 on 2026-07-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_rename_caption_anime_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image_file_id',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Poster Photo File ID'),
        ),
    ]
