# Generated by Django 6.0.7 on 2026-07-31 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0003_anime_image_file_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Janr nomi')),
            ],
            options={
                'verbose_name': 'Janr',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/', verbose_name='Web uchun Poster (Rasm)'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image_file_id',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='Telegram Photo File ID'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.IntegerField(default=1, verbose_name='Fasl'),
        ),
        migrations.AddField(
            model_name='anime',
            name='genres',
            field=models.ManyToManyField(related_name='animes', to='bot_app.genre', verbose_name='Janrlari'),
        ),
    ]
