# Generated by Django 6.0.7 on 2026-08-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0004_genre_anime_poster_alter_anime_image_file_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ismi')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
            ],
            options={
                'verbose_name': 'Telegram Foydalanuvchi',
                'verbose_name_plural': 'Telegram Foydalanuvchilar',
            },
        ),
    ]
